# Generated by Django 4.2.5 on 2023-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='produto_img/%Y/%m')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('promo_price', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('V', 'Vestuário'), ('A', 'Acessório')], default='V', max_length=1)),
            ],
        ),
    ]
