# Generated by Django 4.2.5 on 2023-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_rename_produto_product_rename_variacao_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
